import { execSync } from "child_process"
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "fs"
import { join } from "path"

function run(cmd, cwd) {
  try {
    return execSync(cmd, { cwd: cwd || ".", encoding: "utf-8", maxBuffer: 10 * 1024 * 1024, timeout: 30000 })
  } catch (e) {
    return (e.stdout || "") + (e.stderr || "")
  }
}

export const tools = [
  {
    name: "debug_reproduce",
    description: "Given an error message and code context, generate a minimal standalone reproduction script.",
    inputSchema: {
      type: "object",
      properties: {
        error: { type: "string", description: "Error message or stack trace" },
        context: { type: "string", description: "Relevant code or file paths" }
      },
      required: ["error"]
    }
  },
  {
    name: "debug_stack_walk",
    description: "Parse a stack trace, annotate each frame with source file lines, and identify the root cause frame.",
    inputSchema: {
      type: "object",
      properties: {
        stack: { type: "string", description: "Stack trace string" }
      },
      required: ["stack"]
    }
  },
  {
    name: "debug_log_mine",
    description: "Search log files for error/timeout/crash patterns, returning matched lines with context.",
    inputSchema: {
      type: "object",
      properties: {
        pattern: { type: "string", description: "Error pattern to search for (regex)" },
        path: { type: "string", description: "Log file or directory" },
        context: { type: "number", description: "Lines of context around match (default: 3)" }
      },
      required: ["pattern", "path"]
    }
  },
  {
    name: "debug_bisect_run",
    description: "Run git bisect with a test command to find the commit that introduced a bug.",
    inputSchema: {
      type: "object",
      properties: {
        command: { type: "string", description: "Test command that returns 0 for good, non-zero for bad" },
        good: { type: "string", description: "Known good commit hash" },
        bad: { type: "string", description: "Known bad commit hash (default: HEAD)" }
      },
      required: ["command", "good"]
    }
  },
  {
    name: "debug_guard_inject",
    description: "Generate an assertion/validation guard to prevent a bug from recurring. Returns code at the fix point.",
    inputSchema: {
      type: "object",
      properties: {
        path: { type: "string", description: "File to inject guard into" },
        line: { type: "number", description: "Line number for the guard" },
        condition: { type: "string", description: "Condition the guard should check" }
      },
      required: ["path", "line", "condition"]
    }
  },
  {
    name: "debug_var_watch",
    description: "Set up variable watchpoints — trace when a variable is read or written during execution.",
    inputSchema: {
      type: "object",
      properties: {
        path: { type: "string", description: "File path" },
        varName: { type: "string", description: "Variable name to watch" }
      },
      required: ["path", "varName"]
    }
  }
]

export async function handleTool(name, args) {
  switch (name) {
    case "debug_reproduce": {
      const reproFile = join(process.cwd(), ".apex-repro.js")
      const stackLines = args.error.split("\n").filter(l => l.includes("at "))
      const firstFrame = stackLines[0] || ""
      const fileMatch = firstFrame.match(/\((.*?):(\d+):(\d+)\)/)
      const lang = args.error.includes("TypeError") || args.error.includes("ReferenceError") || args.error.includes("SyntaxError") ? "js" : "ts"
      let repro = ""
      if (lang === "js") {
        repro = `// Reproduction script for: ${args.error.split("\n")[0]}\n// Generated by APEX Debugger\n\nfunction reproduce() {\n  try {\n    // TODO: Insert minimal reproduction code here\n    throw new Error("${args.error.split("\n")[0].replace(/"/g, "'")}")\n  } catch (e) {\n    console.error("Reproduced:", e.message)\n    process.exit(1)\n  }\n}\n\nreproduce()\n`
      } else {
        repro = `// Reproduction script for: ${args.error.split("\n")[0]}\n// Generated by APEX Debugger\n\nfunction reproduce(): void {\n  try {\n    // TODO: Insert minimal reproduction code here\n    throw new Error("${args.error.split("\n")[0].replace(/"/g, "'")}")\n  } catch (e) {\n    console.error("Reproduced:", (e as Error).message)\n    process.exit(1)\n  }\n}\n\nreproduce()\n`
      }
      try { writeFileSync(reproFile, repro) } catch { }
      return {
        content: [{
          type: "text",
          text: `🔬 Reproduction script generated\n\nError: ${args.error.split("\n")[0]}\n\n\`\`\`${lang}\n${repro}\`\`\`\n\nWritten to: ${reproFile}\nRun: node ${reproFile}\n\nRoot cause hint: ${fileMatch ? `${fileMatch[1]}:${fileMatch[2]}` : "Check the stack trace for the first reference to your code (not node_modules)."}`
        }]
      }
    }
    case "debug_stack_walk": {
      const raw = args.stack
      const lines = raw.split("\n").filter(l => l.trim())
      const frames = lines.map((l, i) => {
        const m = l.match(/\s+at\s+(?:(.+?)\s+\()?(.+?):(\d+):(\d+)\)?/)
        if (m) return { frame: i, func: m[1] || "<anonymous>", file: m[2], line: parseInt(m[3]), col: parseInt(m[4]) }
        const m2 = l.match(/\s+at\s+(.+?):(\d+):(\d+)/)
        if (m2) return { frame: i, func: "<anonymous>", file: m2[1], line: parseInt(m2[2]), col: parseInt(m2[3]) }
        return null
      }).filter(Boolean)
      for (const f of frames) {
        try {
          if (existsSync(f.file)) {
            const src = readFileSync(f.file, "utf-8").split("\n")
            if (src[f.line - 1]) f.code = src[f.line - 1].trim()
          }
        } catch { }
      }
      const userFrames = frames.filter(f => !f.file.includes("node_modules") && !f.file.includes("<anonymous>"))
      const rootCause = userFrames[0] || frames[0]
      const table = frames.slice(0, 15).map(f =>
        `| ${f.frame} | ${f.func.substring(0, 25).padEnd(25)} | ${f.file}:${f.line}:${f.col} | ${f.code ? "`" + f.code.substring(0, 50) + "`" : ""} |`
      ).join("\n")
      return {
        content: [{
          type: "text",
          text: `📋 Stack trace analysis\n\n\`\`\`\n${raw.substring(0, 500)}\n\`\`\`\n\n| Frame | Function | Location | Source |\n|-------|----------|----------|--------|\n${table || "No parsable frames found."}\n\n${rootCause ? `🔍 Root cause: Frame ${rootCause.frame} — ${rootCause.file}:${rootCause.line}:${rootCause.col}\n  ${rootCause.func}\n  Code: ${rootCause.code || "N/A"}` : "Could not identify root cause frame."}`
        }]
      }
    }
    case "debug_log_mine": {
      const p = args.path
      if (!existsSync(p)) return { content: [{ type: "text", text: `Path not found: ${p}` }] }
      const ctx = args.context || 3
      const grep = run(`grep -n -C ${ctx} -E "${args.pattern}" "${p}" | head -100`)
      const matches = grep.length
      const table = grep.split("\n").filter(l => l.match(/^\d+[-:]/)).slice(0, 30).map(l => {
        const m = l.match(/^(\d+)([-:])(.*)/)
        return m ? `| ${m[1]} | ${m[3].substring(0, 80)} |` : null
      }).filter(Boolean).join("\n")
      return {
        content: [{
          type: "text",
          text: `📄 Log mining: "/${args.pattern}/" in "${p}"\n\n${table ? `| Line | Content |\n|------|--------|\n${table}` : "No matches found."}\n\nMatches: ${matches > 0 ? grep.split("\n").filter(l => l.match(/^\d+:/)).length : 0} (showing first 30)`
        }]
      }
    }
    case "debug_bisect_run": {
      const hasGit = run("git rev-parse --is-inside-work-tree 2>nul").trim()
      if (!hasGit) return { content: [{ type: "text", text: "Not a git repository." }] }
      const bad = args.bad || "HEAD"
      const output = run(`git bisect start ${bad} ${args.good} 2>&1 && git bisect run ${args.command} 2>&1`, process.cwd())
      const bisectLines = output.split("\n").filter(l => l.includes("is the first bad commit") || l.includes("bisect run success"))
      const culprit = output.match(/([a-f0-9]{7,40}) is the first bad commit/)
      const log = run("git bisect log 2>&1 | head -30")
      return {
        content: [{
          type: "text",
          text: `🔍 Git bisect results\n\nCommand: ${args.command}\nGood: ${args.good}\nBad: ${bad}\n\n${output.substring(0, 1000)}\n\n${culprit ? `\n🔴 First bad commit: ${culprit[1]}` : ""}\n${bisectLines.length > 0 ? `\n✅ Bisect complete.` : "\n⚠️  Bisect may still be in progress."}`
        }]
      }
    }
    case "debug_guard_inject": {
      const fp = args.path
      if (!existsSync(fp)) return { content: [{ type: "text", text: `File not found: ${fp}` }] }
      const content = readFileSync(fp, "utf-8")
      const lines = content.split("\n")
      const indent = lines[Math.min(args.line, lines.length) - 1]?.match(/^\s*/)?.[0] || "  "
      const guard = `// INVARIANT: ${args.condition}\nif (!(${args.condition})) {\n  throw new Error(\`Assertion failed: ${args.condition}\`)\n}\n`
      lines.splice(args.line, 0, guard)
      const newContent = lines.join("\n")
      try { writeFileSync(fp, newContent) } catch (e) {
        return { content: [{ type: "text", text: `Could not write to file: ${e.message}\n\nGenerated guard:\n${guard}` }] }
      }
      return {
        content: [{
          type: "text",
          text: `🛡️ Guard injected into "${args.path}" at line ${args.line}\n\nGuard:\n\`\`\`\n// INVARIANT: ${args.condition}\nif (!(${args.condition})) {\n  throw new Error(\`Assertion failed: ${args.condition}\`)\n}\n\`\`\`\n\n✅ Guard written. The condition \"${args.condition}\" will now be checked before line ${args.line}.`
        }]
      }
    }
    case "debug_var_watch": {
      const fp = args.path
      if (!existsSync(fp)) return { content: [{ type: "text", text: `File not found: ${fp}` }] }
      const content = readFileSync(fp, "utf-8")
      const lines = content.split("\n")
      const refs = []
      for (let i = 0; i < lines.length; i++) {
        const line = lines[i]
        if (line.includes(args.varName)) {
          const type = line.includes("=") && !line.includes("==") && !line.includes("===") ? "WRITE" : "READ"
          refs.push({ line: i + 1, type, code: line.trim().substring(0, 80) })
        }
      }
      const writes = refs.filter(r => r.type === "WRITE")
      const reads = refs.filter(r => r.type === "READ")
      return {
        content: [{
          type: "text",
          text: `👁️ Variable watch: "${args.varName}" in "${args.path}"\n\n| Line | Access | Code |\n|------|--------|------|\n${refs.map(r => `| ${r.line} | ${r.type === "WRITE" ? "✏️  WRITE" : "👁️  READ"} | \`${r.code}\` |`).join("\n")}\n\nSummary: ${writes.length} writes, ${reads.length} reads\n${writes.length > 1 ? `\n⚠️  Variable written in ${writes.length} places — check for unintended mutations.` : ""}`
        }]
      }
    }
    default:
      throw new Error(`Unknown tool: ${name}`)
  }
}
